Rails/Eshopper/config/routes.rb
Rails.application.routes.draw do
  resources :cart_items
  resources :product_categories
  resources :products
  resources :brand_categories
  
  resources :products
  resources :categories do
    resources :brands
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

   root 'home#index'

end

Rails/Eshopper/app/models/brand.rb
class Brand < ActiveRecord::Base
  default_scope  { order(:name => :desc) }
  has_many :brand_categories
  has_many :categories, :through => :brand_categories
  has_many :products
end

Rails/Eshopper/app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @subcategory = @brand.categories
    @categories = Category.all.where(category_id: nil)
    #binding.pry
    @category = Category.find(params[:sub_category] || params[:category_id])
    #binding.pry
    @product = @category.products.where(brand_id: @brand.id)
    
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name, :short_description, :long_description, :status, :category_id)
    end
end

Rails/Eshopper/app/helpers/brands_helper.rb
module BrandsHelper
end

Rails/Eshopper/app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br>
    <%= f.text_field :short_description %>
  </div>
  <div class="field">
    <%= f.label :long_description %><br>
    <%= f.text_area :long_description %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/Eshopper/app/views/brands/_sub_category.html.erb
<div class="category-tab"><!--category-tab-->
  <div class="col-sm-12">
    <ul class="nav nav-tabs">
      <% @subcategory.each_with_index do |subcategory, index| %>
        <% if subcategory.category_id != nil%>
            <li class= <%= 'active' if params[:sub_category].to_s == subcategory.id.to_s%> >
               <%= link_to category_brand_path(sub_category: subcategory.id) do %>
                  <%=subcategory.name%>
               <%end%>
              </li>
        <%end%>
      <% end %>      
    </ul>
  </div>
  <div class="tab-content">
    <div class="tab-pane fade active in" id="tshirt">
      <% @product.each do |product|%>
        <div class="col-sm-3">
          <div class="product-image-wrapper">
            <div class="single-products">
              <div class="productinfo text-center">
                <%= link_to product_path(product)do%>
                  <%= image_tag product.pictures.find_by(imageable_id: product.id).image %>
                  <h2>&#8377; <%=product.price%></h2>               
                  <p><%= truncate(product.name, length: 22, omission: '...') %></p>
                <%end%>
                 <%= link_to "Add to Cart",cart_items_path(product_id: product.id),method: :post, class: "fa fa-shopping-cart btn btn-default add-to-cart"%>
              </div> 
            </div>
          </div>
        </div>
      <%end%>   
    </div>
  </div>
</div><!--/category-tab-->

Rails/Eshopper/app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

Rails/Eshopper/app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Brands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short description</th>
      <th>Long description</th>
      <th>Status</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= brand.short_description %></td>
        <td><%= brand.long_description %></td>
        <td><%= brand.status %></td>
        <td><%= brand.category %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

Rails/Eshopper/app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

Rails/Eshopper/app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>
<section>
      <div class="container">
        <div class="row">
          <div class="col-sm-3">
            <%= render '/commonrender/left_sidebar',locals: {category: @category} %>
          </div>
          <div class="col-sm-9 padding-right">
            <%= render 'sub_category' %>
            <%= render '/commonrender/recommended_items' %>
          </div>
        </div>
      </div>
</section>