Rails/Eshopper/config/routes.rb
Rails.application.routes.draw do
  resources :cart_items
  resources :product_categories
  resources :products
  resources :brand_categories
  
  resources :products
  resources :categories do
    resources :brands
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

   root 'home#index'

end

Rails/Eshopper/app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

Rails/Eshopper/app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cart_item, only: [:show, :edit, :update, :destroy]

  # GET /cart_items
  # GET /cart_items.json
  def index
    @cart_items = CartItem.all
    total = 0.to_i
    @cart_items.each do |item|
      total += item.product.price*item.quantity
      #binding.pry 
    end
  end

  # GET /cart_items/1
  # GET /cart_items/1.json
  def show
  end

  # GET /cart_items/new
  def new
    @cart_item = CartItem.new
  end

  # GET /cart_items/1/edit
  def edit
  end

  # POST /cart_items
  # POST /cart_items.json
  def create
    #@product = Product.all
    @cart_item = CartItem.where(product_id: params[:product_id],user_id: current_user.id).first
    #binding.pry
    if @cart_item.present?
      #binding.pry
      if params[:boolean].present?
        a = params["cart_item"]["quantity"]
        @cart_item.quantity += a.to_i
      else
      @cart_item.quantity += 1
      end
      #@product.quantity -= 1 
    else
      if params[:boolean].present?
        @cart_item = CartItem.new(product_id: params[:product_id],user_id: current_user.id)
        b = params["cart_item"]["quantity"]
        puts @cart_item.quantity
        @cart_item.quantity += b.to_i
        #puts "****************************"
        #puts @cart_item.quantity
      else
        @cart_item = CartItem.new(product_id: params[:product_id],user_id: current_user.id)
        @cart_item.quantity += 1
      end
    end

    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to :back, notice: 'Cart item was successfully created.' }
        format.json { render :show, status: :created, location: @cart_item }
        format.js
      else
        format.html { render :new }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cart_items/1
  # PATCH/PUT /cart_items/1.json
  def update
    @cart_item = CartItem.find(params[:id])
    #binding.pry
    if params[:qty].present?
      @cart_item.quantity -= 1
    else
      @cart_item.quantity += 1
    end
    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to :back, notice: 'Cart item was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart_item }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_items/1
  # DELETE /cart_items/1.json
  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_items_url, notice: 'Cart item was successfully destroyed.' }
      format.json { head :no_content }
      format.js   { render :layout => false}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_item
      #@cart_item = CartItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_item_params
      params.require(:cart_item).permit(:quantity, :user_id, :product_id)
    end
end

Rails/Eshopper/app/helpers/cart_items_helper.rb
module CartItemsHelper
end

Rails/Eshopper/app/views/cart_items/_form.html.erb
<%= form_for(@cart_item) do |f| %>
  <% if @cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
      <% @cart_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/Eshopper/app/views/cart_items/create.js.erb
$("<%= escape_javascript(@cart_item) %>").appendTo("#cart_item");

Rails/Eshopper/app/views/cart_items/destroy.js.erb
$('.delete_item').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});
// debugger
$("#flash").html();

Rails/Eshopper/app/views/cart_items/edit.html.erb
<h1>Editing Cart Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

Rails/Eshopper/app/views/cart_items/index.html.erb
 <section id="cart_items">
  <div class="container">
    <div class="cart_info">
      <table class="table table-condensed">
        <thead>
          <tr class="cart_menu">
            <td class="image">Item</td>
            <td class="product_desc_align"><div class="product_desc_align">Description</div></td>
            <td class="price">Price</td>
            <td class="quantity">Quantity</td>
            <td class="total">Total</td>
            <td></td>
          </tr>
        </thead>
        <tbody>
        <% current_user.cart_items.each do |cart_item| %>
          <tr>
            <td class="cart_product">
              <%= image_tag(cart_item.product.pictures.first.image.url,class: 'cart-image', style: "width:100px;height:100px") %>
            </td>

            <td class="cart_description">
              <h4 class="product_desc_align"><%= cart_item.product.name %></h4>
            </td>

            <td class="cart_price">
              <p>&#8377; <%= cart_item.product.price %></p>
            </td>

            <td class="cart_quantity">
              <div class="cart_quantity_button">
                <!-- <a class="cart_quantity_up" href=""> + </a> -->
                <%= link_to "+", cart_item_path(cart_item),method: :put ,class: "cart_quantity_up", :remote => true %>
                
                <input id="cart_item_count_<%= cart_item.id %>" class="cart_quantity_input" type="number" min="1" max="10" name="quantity" value="<%= cart_item.quantity %>" autocomplete="off" size="2">
                <!-- <a class="cart_quantity_down" href=""> - </a> -->
                <%= link_to "-", cart_item_path(cart_item,qty: "decrease"), method: :put ,class: "cart_quantity_down", :remote => true %>
              </div>
            </td>
            <td class="cart_total" >
              <% @total=cart_item.product.price*cart_item.quantity %>
              <p id="sub_total_<%= cart_item.id %>" class="cart_total_price">&#8377; <%= @total %></p>
            </td>

            <td class="cart_delete">
              <%= link_to cart_item_path(cart_item), method: :delete, data: { confirm: 'you want to delete item from cart?' }, :remote => true, :class => 'delete_item' do %><i class="fa fa-times"></i><% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section> <!--/#cart_items-->
<section id="do_action">
  <div class="container">
    <div class="heading">
      <h3>What would you like to do next?</h3>
      <p>Choose if you have a discount code or reward points you want to use or would like to estimate your delivery cost.</p>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <div class="chose_area">
          <ul class="user_option">
            <li>
              <input type="checkbox">
              <label>Use Coupon Code</label>
            </li>
            <li>
              <input type="checkbox">
              <label>Use Gift Voucher</label>
            </li>
            <li>
              <input type="checkbox">
              <label>Estimate Shipping & Taxes</label>
            </li>
          </ul>
          <ul class="user_info">
            <li class="single_field">
              <label>Country:</label>
              <select>
                <option>United States</option>
                <option>Bangladesh</option>
                <option>UK</option>
                <option>India</option>
                <option>Pakistan</option>
                <option>Ucrane</option>
                <option>Canada</option>
                <option>Dubai</option>
              </select>
              
            </li>
            <li class="single_field">
              <label>Region / State:</label>
              <select>
                <option>Select</option>
                <option>Dhaka</option>
                <option>London</option>
                <option>Dillih</option>
                <option>Lahore</option>
                <option>Alaska</option>
                <option>Canada</option>
                <option>Dubai</option>
              </select>
            
            </li>
            <li class="single_field zip-field">
              <label>Zip Code:</label>
              <input type="text">
            </li>
          </ul>
          <a class="btn btn-default update" href="">Get Quotes</a>
          <a class="btn btn-default check_out" href="">Continue</a>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="total_area">
          <ul>
            <li>Cart Sub Total <span>$59</span></li>
            <li>Eco Tax <span>$2</span></li>
            <li>Shipping Cost <span>Free</span></li>
            <li>Total <span>$61</span></li>
          </ul>
            <a class="btn btn-default update" href="">Update</a>
            <a class="btn btn-default check_out" href="">Check Out</a>
        </div>
      </div>
    </div>
  </div>
</section><!--/#do_action-->

Rails/Eshopper/app/views/cart_items/new.html.erb
<h1>New Cart Item</h1>

<%= render 'form' %>

<%= link_to 'Back', cart_items_path %>

Rails/Eshopper/app/views/cart_items/update.js.erb
$('#cart_item_count_'+<%= @cart_item.id %>).val(<%= @cart_item.quantity%>)
$('#sub_total_'+<%= @cart_item.id %>).html('&#8377 '+<%= @cart_item.quantity*@cart_item.product.price%>)